name: tnregression
dependencies:
  - python=3.12
  - pip
  - pip:
    - matplotlib==3.10.1
    - networkx==3.4.2
    - numpy==2.2.4
    - pandas==2.2.3
    - pillow==11.2.0
    - pydantic==2.11.1
    - pydantic_core==2.33.0
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - sympy==1.13.3
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - torch==2.5.1
    - tqdm==4.67.1
    - triton==3.1.0
    - ucimlrepo==0.0.7
