name: tnregression
dependencies:
  - python=3.12
  - pip
  - pip:
    - matplotlib==3.10.1
    - networkx==3.4.2
    - numpy==2.2.4
    - pandas==2.2.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - torch==2.5.1
    - tqdm==4.67.1
